services:
  - type: web
    name: cv-optimizer-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        fromDatabase:
          name: cv-optimizer-db
          property: connectionString
      - key: OPENROUTER_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: false

databases:
  - name: cv-optimizer-db
    databaseName: cv_optimizer_pro
    user: cv_user
    plan: free